language: php
php:
  - 5.6
services:
  - mysql
before_script:
  # database creation
  - mysql -e "create database symfony;"
  - composer install --no-interaction
  - npm install -g casperjs
script:
  - php -S 127.0.0.1:8000 &
  - php codecept.phar run
  - php app/console doctrine:schema:create
  - casperjs test AcceptanceTests/uploadForm.js