services:
    galerija_api.images.image_manipulation:
        class: Galerija\APIBundle\Images\ImageManipulationService
        arguments: [@doctrine.orm.entity_manager, 'GalerijaAPIBundle:Image', @liip_imagine.gd, "@=service('knp_gaufrette.filesystem_map').get('pictures')"]
