services:
    galerija_api.images.image_manipulation:
        class: Galerija\APIBundle\Images\ImageManipulationService
        arguments: [@doctrine.orm.entity_manager, 'GalerijaAPIBundle:Image', @liip_imagine.gd, %assetic.write_to%]
