services:
    galerija_api.images.image_manipulation:
        class: Galerija\APIBundle\Images\ImageManipulationService
        arguments: [@doctrine.orm.entity_manager, 'GalerijaAPIBundle:Image', @liip_imagine.gd, @galerija_api.images.storage]

    galerija_api.images.storage:
        class: Galerija\APIBundle\Images\ImageStoreService
        arguments: [@knp_gaufrette.filesystem_map, @request_stack, @galerija_api.dropbox.oauth]

    galerija_api.dropbox.oauth:
        class: Dropbox_OAuth_Curl
        arguments: [%galerija_api.dropbox.key%, %galerija_api.dropbox.secret%]
        calls:
            - [setToken, ["%galerija_api.dropbox.token%", "%galerija_api.dropbox.token_secret%"]]

    galerija_api.dropbox.api:
        class: Galerija\APIBundle\Images\DropboxAPI
        arguments: [@galerija_api.dropbox.oauth, "sandbox"]